### ISSUE TITLE
/rain stop in PvP

### ISSUE THREAD

**Issue by Fraxo** [popstarfreas/DG-TS#57] opened 2019-06-23 05:07 UTC
Allow crew to use /rain stop in PvP, or set a broadcast that automatically uses /rain stop every so often, as rain causes lag, reduces visibility excessively, and adds a lot of background noise

**Comment by KceGio** [comment] 2019-06-23 06:27
Duplicate of [Issue #13](https://github.com/popstarfreas/DG-TS/issues/13)

**Closed** 2019-06-23 06:30 UTC
